version: '3.7'
services:
    app:
        image: misbahmehmood/sfia1
        build: .
        ports:
        - target: 5000
          published: 5000
          protocol: tcp
        deploy:
          replicas: 1
        environment:
            FLASK_PROJECT_DB_URI: ${FLASK_PROJECT_DB_URI}
            SECRET_KEY: ${SECRET_KEY}